name: vaptic
description: Mobile companion app for haptic vest

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue: ^0.6.3
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.6
  uuid: ^2.0.4
  flutter_svg: ^0.17.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Icons
      fonts:
        - asset: assets/Icons.ttf
  assets:
    - assets/Vest.svg
    - assets/icon.png
